# Generated by Django 4.1.1 on 2022-09-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img_article',
            field=models.ImageField(blank=True, null=True, upload_to='images/img_article'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text_article',
            field=models.TextField(blank=True),
        ),
    ]
