# Generated by Django 4.1.1 on 2022-11-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_section',
            field=models.CharField(choices=[('финансы', 'финансы'), ('космос', 'космос'), ('IT', 'IT'), ('искусство', 'искусство'), ('природа', 'природа'), ('дизайн', 'дизайн'), ('игры', 'игры'), ('другое', 'другое')], default='другое', max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
