# Generated by Django 4.1.1 on 2022-09-16 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_img_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 8, 41, 35, 9454, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text_article',
            field=models.TextField(),
        ),
    ]
