# Generated by Django 4.1.1 on 2022-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_img_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img_article',
            field=models.ImageField(blank=True, null=True, upload_to='imgarticles/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text_article',
            field=models.TextField(),
        ),
    ]
