# Generated by Django 4.1.1 on 2022-09-16 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articles_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 11, 50, 2, 625009), editable=False),
        ),
    ]
