# Generated by Django 4.1.1 on 2022-09-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articles_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img_article',
            field=models.ImageField(blank=True, null=True, upload_to='imgarticles/'),
        ),
    ]
