# Generated by Django 4.1.1 on 2022-11-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_remove_userprofile_user_name_userprofile_date_change_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
